					<h2>Expresión Regular</h2><hr /> 
					<div class="post-body">
                                            <form method="post" action="<?php echo $cfg['base_url'] ?>/">
                                                <p>Ingrese la expresión regular que será utilizada por el programa para generar el analizador sintátctico.</p>
                                                <input type="text" name="regex" /><br />
                                                <input type="submit" value="Ingresar la Expresión Regular">
                                            </form>
                                            <h3>Operadores permitidos:</h3>
                                            <p> <b>*</b>: Clausura de Kleene.<br />
                                            	<b>|</b>: Operador de unión.<br />
                                            	<b>()</b>: Paréntesis de agrupación.<br />
                                    			<br />Ejemplo: <b>a(a|b)*|c</b></p>
                                        </div>
