					<h2>AFND-ε generado por algoritmo de Thompson</h2><hr /> 
					<div class="post-body">
                                                <img style="width: 632px;" src="<?php echo $cfg['base_url'] ?>/main/imprimir_afnd" alt="AFND-ε" /><br /><br />
                                                <?php pr($tabla) ?>
                                        </div>
                                        
